apiVersion: v1
kind: ConfigMap
metadata:
  name: stocklive-config
  namespace: stockportfolio
data:
  POSTGRES_HOST: "ep-royal-thunder-45099107-pooler.us-east-1.postgres.vercel-storage.com"
  POSTGRES_DATABASE: "verceldb"
  POSTGRES_USER: "default"
  FRONTEND_ORIGIN: "http://localhost:3000"
  VITE_API_BASE_URL: "/api"
---
apiVersion: v1
kind: Secret
metadata:
  name: stocklive-secrets
  namespace: stockportfolio
type: Opaque
stringData:
  POSTGRES_PASSWORD: "QhYas0zXyE7A"
  MAIL_USERNAME: "mastinder.dnbi@gmail.com"
  MAIL_PASSWORD: "jvwh iprf cbeq fmql"
  SECRET_KEY: "your-secret-key-change-in-production"
  POSTGRES_URL: "postgres://default:QhYas0zXyE7A@ep-royal-thunder-45099107-pooler.us-east-1.postgres.vercel-storage.com/verceldb"
  DD_API_KEY: "8edfbfb9a7e08dd348d035ac32492341"
  DD_APP_KEY: "6eb3582d9dac8b7a4efdbe6ad642f7ee057dce26"