apiVersion: v1
kind: ConfigMap
metadata:
  name: stocklive-config
  namespace: default
data:
  POSTGRES_HOST: "ep-royal-thunder-45099107-pooler.us-east-1.postgres.vercel-storage.com"
  POSTGRES_DATABASE: "verceldb"
  POSTGRES_USER: "default"
  FRONTEND_ORIGIN: "http://localhost:3000"
  VITE_API_BASE_URL: "/api"
---
apiVersion: v1
kind: Secret
metadata:
  name: stocklive-secrets
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: "QhYas0zXyE7A"
  MAIL_USERNAME: "mastinder.dnbi@gmail.com"
  MAIL_PASSWORD: "jvwh iprf cbeq fmql"
  SECRET_KEY: "your-secret-key-change-in-production"
  POSTGRES_URL: "postgres://default:QhYas0zXyE7A@ep-royal-thunder-45099107-pooler.us-east-1.postgres.vercel-storage.com/verceldb"