apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocklive-backend
  namespace: default
  labels:
    app: stocklive-backend
    service: stocklive-backend
    version: v1.0.0
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: stocklive-backend
    tags.datadoghq.com/version: v1.0.0
  annotations:
    admission.datadoghq.com/python-lib.version: "v3.15.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stocklive-backend
  template:
    metadata:
      labels:
        app: stocklive-backend
        service: stocklive-backend
        version: v1.0.0
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: stocklive-backend
        tags.datadoghq.com/version: v1.0.0
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/backend.logs: '[{"source":"python","service":"stocklive-backend","log_processing_rules":[{"type":"multi_line","name":"log_start_with_date","pattern":"\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])"}]}]'
        ad.datadoghq.com/backend.checks: |
          {
            "http_check": {
              "init_config": {},
              "instances": [
                {
                  "url": "http://%%host%%:8000/",
                  "name": "stocklive-backend-health"
                }
              ]
            }
          }
        admission.datadoghq.com/python-lib.version: "v3.15.0"
    spec:
      containers:
      - name: backend
        image: stocklive-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "stocklive-backend"
        - name: DD_VERSION
          value: "v1.0.0"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_URL
          value: "http://$(DD_AGENT_HOST):8126"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_SAMPLE_RATE
          value: "1"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: stocklive-config
        - secretRef:
            name: stocklive-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stocklive-backend-service
  namespace: default
spec:
  selector:
    app: stocklive-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP