version: '3.8'

services:
  backend:
    build: 
      context: ../../backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FRONTEND_ORIGIN=http://localhost:8080
    env_file:
      - ../../.env
    networks:
      - stocklive-network
    restart: unless-stopped

  frontend:
    build: 
      context: ../../
      dockerfile: ./frontend/Dockerfile
      args:
        - VITE_API_BASE_URL=/api
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - stocklive-network
    restart: unless-stopped

networks:
  stocklive-network:
    driver: bridge

volumes:
  postgres_data: